# Generated by Django 4.0.5 on 2022-07-19 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modeldevice',
            old_name='value',
            new_name='retail_model',
        ),
        migrations.AlterUniqueTogether(
            name='modeldevice',
            unique_together={('manufacturer', 'retail_model')},
        ),
    ]
