# Generated by Django 4.0.5 on 2022-07-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_rename_value_modeldevice_retail_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileoperator',
            name='country_cody',
            field=models.CharField(max_length=5, null=True, verbose_name='Country short name'),
        ),
        migrations.AddField(
            model_name='mobileoperator',
            name='mcc',
            field=models.CharField(max_length=20, null=True, verbose_name='Mobile Country Code'),
        ),
        migrations.AddField(
            model_name='mobileoperator',
            name='mnc',
            field=models.CharField(max_length=20, null=True, verbose_name='Mobile Network Code'),
        ),
    ]
