# Generated by Django 4.0.5 on 2022-07-22 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_mobileoperator_country_cody_mobileoperator_mcc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.mobileoperator'),
        ),
    ]
