# Generated by Django 4.0.5 on 2022-07-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_rename_country_cody_mobileoperator_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='title',
            field=models.CharField(choices=[('RUS', 'Russia'), ('UA', 'Ukraine'), ('GE', 'Georgia')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='firstname',
            name='value',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='lastname',
            name='value',
            field=models.CharField(max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterUniqueTogether(
            name='firstname',
            unique_together={('value', 'gender')},
        ),
        migrations.AlterUniqueTogether(
            name='lastname',
            unique_together={('value', 'gender')},
        ),
    ]
