# Generated by Django 4.1 on 2022-08-13 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0007_alter_country_title_region_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
