# Generated by Django 4.1 on 2022-08-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0009_region_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='proxies',
            field=models.ManyToManyField(to='workers.proxy'),
        ),
    ]
