# Generated by Django 4.1 on 2022-08-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0010_task_proxies'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='proxy_protocol',
            field=models.CharField(choices=[('socks5', 'Socks5'), ('https', 'Https')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='proxy_type',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('static', 'Static')], max_length=20, null=True),
        ),
    ]
