# Generated by Django 4.1 on 2022-09-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0011_proxy_proxy_protocol_alter_proxy_proxy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
