# Generated by Django 4.1 on 2022-09-04 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0014_worker_ipaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='name',
            new_name='hostname',
        ),
    ]
