# Generated by Django 4.1 on 2022-09-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0016_rename_date_created_operation_time_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('no_sms', 'No Sms'), ('failed', 'Failed'), ('completed', 'Completed')], default='new', max_length=50),
        ),
    ]
