# Generated by Django 4.1 on 2022-09-04 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0017_operation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='type',
        ),
    ]
