# Generated by Django 4.0.5 on 2022-09-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0018_remove_operation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='time_last_change',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('started', 'Started'), ('requested', 'Requested'), ('no_sms', 'No Sms'), ('got_sms', 'Got Sms'), ('failed', 'Failed'), ('completed', 'Completed')], default='new', max_length=50),
        ),
    ]
