# Generated by Django 4.1 on 2022-09-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0019_operation_time_last_change_alter_operation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='title',
            field=models.CharField(choices=[('RU', 'Russia'), ('UA', 'Ukraine'), ('GE', 'Georgia'), ('BY', 'Belarus'), ('EU', 'Combine Europe')], max_length=100, null=True),
        ),
    ]
