# Generated by Django 4.1 on 2022-09-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0020_alter_country_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='title',
            field=models.CharField(choices=[('RU', 'Russia'), ('UA', 'Ukraine'), ('GE', 'Georgia'), ('BY', 'Belarus'), ('EU', 'Europe')], max_length=100, null=True),
        ),
    ]
