# Generated by Django 4.0.5 on 2022-07-19 13:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidBuildVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('build', models.CharField(max_length=50, null=True, unique=True)),
                ('tag', models.CharField(db_index=True, max_length=80, null=True, verbose_name='Тэг сборки')),
                ('version', models.CharField(choices=[('Android9', 'Android9'), ('Android10', 'Android10'), ('Android11', 'Android11')], max_length=50, null=True, verbose_name='Версия андройд')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(choices=[('RUS', 'Russia'), ('UA', 'Ukraine'), ('BLR', 'Belarus'), ('GE', 'Georgia')], max_length=100, null=True)),
                ('short_title', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='FirstName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100, null=True, unique=True, verbose_name='Имя')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=15)),
            ],
            options={
                'db_table': 'workers_first_name',
            },
        ),
        migrations.CreateModel(
            name='LastName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100, null=True, unique=True, verbose_name='Фамилия')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=15)),
            ],
            options={
                'db_table': 'workers_last_name',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('value', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, null=True)),
                ('short_title', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=50, null=True, unique=True)),
                ('operator', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(max_length=3, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.country')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service', to='workers.service')),
            ],
            options={
                'unique_together': {('service', 'value', 'operator')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('reg', 'Registration'), ('auth', 'Authentication'), ('milk', 'Milking')], max_length=50, null=True, verbose_name='Тип операции')),
                ('token', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token', to='workers.token')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('reg', 'Registration'), ('auth', 'Authentication'), ('milk', 'Milking')], max_length=50, null=True, verbose_name='Тип операции')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation', to='workers.task')),
            ],
        ),
        migrations.CreateModel(
            name='MobileOperator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, null=True)),
                ('country', models.ForeignKey(max_length=3, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.country')),
            ],
            options={
                'db_table': 'workers_mobile_operator',
            },
        ),
        migrations.CreateModel(
            name='LastNameCountry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workers.country')),
                ('last_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workers.lastname')),
            ],
            options={
                'db_table': 'workers_last_name_country',
                'unique_together': {('last_name', 'country')},
            },
        ),
        migrations.AddField(
            model_name='lastname',
            name='country',
            field=models.ManyToManyField(max_length=3, through='workers.LastNameCountry', to='workers.country'),
        ),
        migrations.CreateModel(
            name='FirstNameCountry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workers.country')),
                ('first_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workers.firstname')),
            ],
            options={
                'db_table': 'workers_first_name_country',
                'unique_together': {('first_name', 'country')},
            },
        ),
        migrations.AddField(
            model_name='firstname',
            name='country',
            field=models.ManyToManyField(max_length=3, through='workers.FirstNameCountry', to='workers.country'),
        ),
        migrations.CreateModel(
            name='BaseAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=30, null=True, unique=True)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('birth_day', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=15)),
                ('city', models.CharField(blank=True, max_length=90)),
                ('base_latitudes', models.CharField(max_length=100, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workers.country')),
            ],
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('port', models.CharField(max_length=10, null=True)),
                ('proxy_type', models.CharField(choices=[('socks5', 'Socks5'), ('https', 'Https')], max_length=20, null=True)),
                ('last_active_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.country')),
            ],
            options={
                'verbose_name_plural': 'Proxies',
                'unique_together': {('login', 'password', 'address', 'port')},
            },
        ),
        migrations.CreateModel(
            name='ModelDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100, null=True, unique=True)),
                ('device', models.CharField(max_length=50, null=True)),
                ('model', models.CharField(max_length=50, null=True, unique=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.manufacturer')),
            ],
            options={
                'db_table': 'workers_model_device',
                'unique_together': {('manufacturer', 'value')},
            },
        ),
    ]
