# Generated by Django 4.1 on 2022-09-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0013_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='ipaddress',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
