# Generated by Django 4.1 on 2022-09-04 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0015_rename_name_worker_hostname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='date_created',
            new_name='time_created',
        ),
        migrations.AddField(
            model_name='operation',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='workers.worker'),
        ),
    ]
